# Imagem base python para poder executar o app FastApi
FROM python:3.9

# Diretório dentro da imagem que vamos trabalhar
WORKDIR /app

#copia o arquivo requirements.txt para dentro do diretorio dentro da imagem
COPY ./requirements.txt /app/requirements.txt

#instala as bibliotecas do requirements
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

#copia os arquivos todos para o diretorio dentro da imagem
COPY . /app

#comando de inicialização do app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]